export { AddStickers } from './AddStickers/AddStickers';
export { CartPage } from './CartPage/CartPage';
export { ChangePasswordPage } from './ChangePasswordPage/ChangePasswordPage';
export { MainPage } from './MainPage/MainPage';
export { OrdersPage } from './OrdersPage/OrdersPage';
export { PageNotFound } from './PageNotFound/PageNotFound';
export { PolicyPage } from './PolicyPage/PolicyPage';
export { ProfilePage } from './ProfilePage/ProfilePage';
export { VerifyEmail } from './VerifyEmail/VerifyEmail';
