import image from '../../../images/logo.svg';

export const cards = [
  {
    image: image,
    id: 9,
    size: { width: 100, height: 100 },
    shape: 'rounded-square',
    white_border: true,
  },
  {
    image: image,
    id: 10,
    size: { width: 100, height: 100 },
    shape: 'rounded-square',
    white_border: true,
  },
  {
    image: image,
    id: 11,
    size: { width: 130, height: 130 },
    shape: 'rounded-square',
    white_border: true,
  },
  {
    image: image,
    id: 12,
    size: { width: 130, height: 130 },
    shape: 'square',
    white_border: true,
  },
  {
    image: image,
    id: 6,
    size: { width: 130, height: 130 },
    shape: 'rounded-square',
    white_border: true,
  },
  {
    image: image,
    id: 18,
    size: { width: 130, height: 130 },
    shape: 'rounded-square',
    white_border: true,
  },
  { image: image, id: 17, size: { width: 130, height: 130 }, shape: 'square', white_border: true },
  {
    image: image,
    id: 1,
    size: { width: 200, height: 200 },
    shape: 'square',
    white_border: true,
  },
  { image: image, id: 2, size: { width: 200, height: 200 }, shape: 'circle', white_border: true },
  {
    image: image,
    id: 4,
    size: { width: 200, height: 200 },
    shape: 'rounded-square',
    white_border: true,
  },
  {
    image: image,
    id: 3,
    size: { width: 240, height: 240 },
    shape: 'rounded-square',
    white_border: true,
  },
  {
    image: image,
    id: 8,
    size: { width: 240, height: 240 },
    shape: 'rounded-square',
    white_border: true,
  },
  { image: image, id: 7, size: { width: 250, height: 250 }, shape: 'circle', white_border: true },
  {
    image: image,
    id: 33,
    size: { width: 250, height: 250 },
    shape: 'rounded-square',
    white_border: true,
  },
  {
    image: image,
    id: 5,
    size: { width: 350, height: 350 },
    shape: 'rounded-square',
    white_border: true,
  },
  {
    image: image,
    id: 16,
    size: { width: 350, height: 350 },
    shape: 'circle',
    white_border: true,
  },
  {
    image: image,
    id: 30,
    size: { width: 100, height: 100 },
    shape: 'rounded-square',
    white_border: true,
  },
  {
    image: image,
    id: 31,
    size: { width: 100, height: 100 },
    shape: 'rounded-square',
    white_border: true,
  },
  {
    image: image,
    id: 32,
    size: { width: 130, height: 130 },
    shape: 'rounded-square',
    white_border: true,
  },
];
